# Generated by Django 4.1.4 on 2022-12-25 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_parent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imei1',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxLengthValidator(13), django.core.validators.MinLengthValidator(1)]),
        ),
    ]
