# Generated by Django 4.1.4 on 2022-12-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='This is deleted datetime ', null=True, verbose_name='Deleted Datetime '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='This is deleted datetime ', null=True, verbose_name='Deleted Datetime '),
        ),
    ]
