# Generated by Django 4.1.4 on 2022-12-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_address_deleted_at_alter_profile_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to='profile/%Y/%m/%d'),
        ),
    ]
